added my description
ScPo-CompEcon/Students pull request #34
Opened 2021-01-29 18:13 UTC by popohacker

2021-02-01 15:29 UTC, floswald requested changes

2021-02-01 15:29 UTC, floswald commented on _data/spring_2021/popohacker.json
> +{\*\expandedcolortbl;;\cssrgb\c14118\c16078\c18039;}
you can see a bunch of stuff that your editor seems to have introduced. none of this is valid code. consider using a different editor. your json needs to look *exactly* like in the example.

2021-02-02 14:41 UTC, floswald commented
only missing a profile picture now!

2021-02-02 14:56 UTC, popohacker commented
I added it !

Le mar. 2 févr. 2021 à 15:41, Florian Oswald <notifications@github.com> a
écrit :

> only missing a profile picture now!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ScPo-CompEcon/Students/pull/34#issuecomment-771681649>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOWZPB3RGIT5QW6P4O5U7DLS5AFKJANCNFSM4WZIRHZA>
> .
>

2021-02-02 15:09 UTC, floswald approved these changes

2021-02-02 15:09 UTC, merged